################################################################################
##      Copyright (C) 2020        Sebastian Francisco Colomar Bauza           ##
##      Copyright (C) 2020        Alejandro Colomar Andrés                    ##
##      SPDX-License-Identifier:  GPL-2.0-only                                ##
################################################################################
name: CI-push

on:
    pull_request:
        branches:
        -
            main
    push:
        branches:
        -
            main
jobs:
    sshd_config:
        runs-on: ubuntu-20.04
        steps:
        -
            name: checkout
            uses: actions/checkout@v2
        -
            name: docker-run
            run: docker run -dt --name test ubuntu:20.04;
        -
            name: apt-get update
            run: docker exec test apt-get update;
        -
            name: apt-get install openssh-server
            run: |
                docker exec test                                        \
                    apt-get install -y --no-install-recommends openssh-server;
        -
            name: cp sshd_config
            run: docker cp etc/ssh/sshd_config test:/etc/ssh;
        -
            name: service ssh restart
            run: docker exec test service ssh restart;
        -
            name: 'TEST: service ssh status'
            run: docker exec test service ssh status | grep "sshd is running";
    sshd-scripts:
        needs: sshd_config
        runs-on: ubuntu-20.04
        steps:
        -
            name: checkout
            uses: actions/checkout@v2
        -
            name: docker-run
            run: docker run -dt --name test ubuntu:20.04;
        -
            name: Adapt install_basic.sh
            run: sed -i '/^user=/s/=.*/="root";/' ./bin/install_basic.sh;
        -
            name: cp install_basic.sh
            run: docker cp ./bin/install_basic.sh test:./;
        -
            name: run install_basic.sh
            run: docker exec test bash ./install_basic.sh;
        -
            name: ./libexec/ssh/secure_ssh.sh
            run: docker exec test /usr/local/src/server/libexec/ssh/secure_ssh.sh;
        -
            name: 'TEST: service ssh status'
            run: docker exec test service ssh status | grep "sshd is running";
################################################################################
